[{'id': 9519792, 'name': '<em>深圳市腾讯计算机系统有限公司</em>', 'type': 1, 'matchType': '公司名称匹配', 'base': '广东',
  'legalPersonName': '马化腾', 'estiblishTime': '1998-11-11 00:00:00.0', 'regCapital': '6500万人民币', 'regStatus': '存续',
  'score': '85', 'orginalScore': '8525', 'bonusScore': '0', 'companyScore': '85', 'historyNames': None,
  'categoryCode': '', 'industry': None,
  'humanNames': '奚丹\t:#0\t;\t卢山\t:#0\t;\t马化腾\t:#0\t;\t周昭钦\t:#0\t;\t许晨晔\t:#0\t;\t黄秋华\t:#0\t;\t刘华\t:#0\t;\t马化腾\t:#1\t;\t张志东\t:#1\t;\t陈一丹\t:#1\t;\t许晨晔\t:#1\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None,
  'bondType': None, 'newtestName': None, 'regNumber': '440301103448669', 'orgNumber': '70846113-6',
  'creditCode': '91440300708461136T',
  'businessScope': '计算机软;硬件的设计;技术开发;销售;数据库及计算机网络服务;国内商业;物资供销业;从事广告业务;另行办理审批登记后方可经营;货物及技术进出口;票务代理;第一类增值电信业务中的国内互联网虚拟专用网业务;第二类增值电信业务中的国内多方通信服务业务;国内呼叫中心业务;信息服务业务;网络游戏出版运营;互联网新闻信息转载服务;预包装食品销售;利用信息网络经营音乐娱乐产品;游戏产品;含网络游戏虚拟货币发行;艺术品;演出剧;节;目;动漫产品;表演;从事网络文化产品的展览;比赛活动;互联网视听节目服务;制作;复制;发行电视剧;动画片;制作须另申报;专题;专栏;综艺;出版物零售',
  'regLocation': '深圳市南山区粤海街道麻岭社区科技中一路腾讯大厦35层', 'phone': '0755-86013388\t;\t07558601****',
  'phoneList': ['0755-8601****'],
  'phoneInfoList': [{'number': '0755-86013388', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'}],
  'businessItemList': None, 'phoneNum': '0755-8601****',
  'logo': 'https://img5.tianyancha.com/logo/lll/4962ef744e5f1100be3a9368617abdf5.png@!f_200x200', 'city': '深圳市',
  'district': '南山区', 'emails': '2870979233@qq.com\t;\t240747163@qq.com\t;\tlandyzhang@tencent.com',
  'emailList': ['2870979233@qq.com', '240747163@qq.com', 'landyzhang@tencent.com'],
  'websites': 'http://www.tencent.com\t;\tflzhan.com\t;\ttdnsdp4.cn\t;\ttlivecdn.com.cn\t;\ttencentciam.com.cn\t;\tfynb.net\t;\ttencentresearch.com\t;\tdcloudvod.com\t;\ttliveplay.com\t;\ttsm-license.com\t;\ttdnsstic4.cn\t;\tizhuye.flzhan.cn\t;\tizhuye.flzhan.com\t;\tizhuye.tlivecdn.com.cn\t;\tizhuye.tencentciam.com.cn\t;\tizhuye.fynb.net\t;\tizhuye.tencentresearch.com\t;\tizhuye.dcloudvod.com\t;\tizhuye.tsm-license.com\t;\twww.qq.com',
  'hiddenPhones': None, 'abbr': '微信发票助手\t:#1#\t;\t腾讯控股\t:#1#\t;\t识花君\t:#1#\t;\t腾讯投资\t:#2#\t;\t', 'tagList': None,
  'companyType': 1, 'companyOrgType': '有限责任公司\t;\t有限责任公司', 'labelList': None, 'matchField': None, 'latitude': None,
  'longitude': None, 'legalPersonId': '2277807374', 'legalPersonType': '1', 'distance': None,
  'categoryStr': '软件和信息技术服务业', 'isClaimed': 0, 'claimPkgType': -2, 'realClaimPkgType': None, 'baiduUrl': None,
  'isBranch': 0, 'alias': '腾讯', 'claimInfo': None, 'hidden': 0, 'legalPersonShowStr': '法定代表人',
  'regCapitalShowStr': '注册资本', 'estiblishTimeShowStr': '成立日期', 'multiMatchField': [],
  'labelListV2': ['战略融资', '腾讯控股', '投资机构', '企业集团', '高新技术企业', '独角兽企业', '火炬计划项目企业'],
  'labelJsonList': ['{"type":1,"value":"战略融资"}', '{"type":1,"value":"腾讯控股"}', '{"type":1,"value":"投资机构"}',
                    '{"type":1,"value":"企业集团"}', '{"type":1,"value":"高新技术企业"}', '{"type":1,"value":"独角兽企业"}',
                    '{"type":1,"value":"火炬计划项目企业"}'], 'taxCode': '91440300708461136T',
  'socialSecurityStaff_num': '7031', 'categoryCodeStd': '651', 'hasMorePhone': None, 'hasVideo': None, 'videoId': None,
  'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人', 'secondPositionShowStr': '注册资本',
  'firstPositionValue': '马化腾', 'secondPositionValue': '6500万人民币', 'bizType': '7',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[0,0,11,190]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '6500.0', 'establish_time_long': '910713600000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 37009, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 30680, 'historyRiskCount': 188, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 13593411, 'name': '华谊兄弟传媒股份<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '浙江',
  'legalPersonName': '王忠军', 'estiblishTime': '2004-11-19 00:00:00.0', 'regCapital': '277450.5919万人民币',
  'regStatus': '存续', 'score': '98', 'orginalScore': '9895', 'bonusScore': '0', 'companyScore': '98',
  'historyNames': None, 'categoryCode': '', 'industry': None,
  'humanNames': '李青\t:#0\t;\t高辉\t:#0\t;\t丁琪\t:#0\t;\t高海江\t:#0\t;\t刘晓梅\t:#0\t;\t王忠军\t:#0\t;\t王忠磊\t:#0\t;\t吴鹰\t:#0\t;\t盛希泰\t:#0\t;\t王夫也\t:#0\t;\t杨涛\t:#0\t;\t张帆\t:#0\t;\t王忠军\t:#1\t;\t王忠磊\t:#1\t;\t马云\t:#1\t;\t鲁伟鼎\t:#1\t;\t黄立平\t:#1\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': '华谊兄弟',
  'bondNum': '300027', 'bondType': 'A股', 'newtestName': None, 'regNumber': '330783000004500', 'orgNumber': '76869118-7',
  'creditCode': '91330000768691187H',
  'businessScope': '制作;复制;专题;专栏;综艺;动画片;广播剧;电视剧;广播电视节目制作经营许可证;国产影片发行;摄制电影;单片;企业形象策划;影视文化信息咨询服务;影视广告制作;代理;发行;影视项目的投资管理;经营进出口业务;实业投资;投资管理;资产管理;投资咨询;企业管理咨询;经济信息咨询',
  'regLocation': '浙江省东阳市横店影视产业实验区C1-001', 'phone': '0579-86587019\t;\t010-65805818\t;\t057986587019\t;\t0106580****',
  'phoneList': ['0579-8658****', '010-6580****'],
  'phoneInfoList': [{'number': '0579-86587019', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '010-65805818', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'}],
  'businessItemList': None, 'phoneNum': '0579-8658****',
  'logo': 'https://img5.tianyancha.com/logo/lll/19533c8e5d682d887290f3b6df1ef820.png@!f_200x200', 'city': '金华市',
  'district': '东阳市', 'emails': 'may.wang@huayimedia.com', 'emailList': ['may.wang@huayimedia.com'],
  'websites': 'http://www.huayimedia.com/', 'hiddenPhones': None, 'abbr': '华谊兄弟\t:#1#\t;\t华谊兄弟\t:#2#\t;\t',
  'tagList': None, 'companyType': 1, 'companyOrgType': '股份有限公司\t;\t股份有限公司(上市、自然人投资或控股)', 'labelList': None,
  'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None, 'longitude': None,
  'legalPersonId': '2070666347', 'legalPersonType': '1', 'distance': None, 'categoryStr': '广播、电视、电影和录音制作业',
  'isClaimed': 0, 'claimPkgType': -2, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': '华谊兄弟',
  'claimInfo': None, 'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本',
  'estiblishTimeShowStr': '成立日期', 'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}],
  'labelListV2': ['定向增发', 'A股 | 正常上市', '华谊兄弟', '投资机构', '企业集团', '小微企业'], 'labelJsonList': ['{"type":1,"value":"定向增发"}',
                                                                                          '{"bondType":"A股","listingStatus":"正常上市","bondNum":"300027","sort":1,"type":2,"shortName":"华谊兄弟","value":"A股 | 正常上市"}',
                                                                                          '{"type":1,"value":"华谊兄弟"}',
                                                                                          '{"type":1,"value":"投资机构"}',
                                                                                          '{"type":1,"value":"企业集团"}',
                                                                                          '{"type":1,"value":"小微企业"}'],
  'taxCode': '91330000768691187H', 'socialSecurityStaff_num': '7', 'categoryCodeStd': '863', 'hasMorePhone': None,
  'hasVideo': None, 'videoId': None, 'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人',
  'secondPositionShowStr': '注册资本', 'firstPositionValue': '王忠军', 'secondPositionValue': '277450.5919万人民币',
  'bizType': '8', 'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '277450.5919', 'establish_time_long': '1100793600000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 555, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 40247, 'historyRiskCount': 9, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 2313221010, 'name': '财付通支付科技<em>有限公司</em>', 'type': 1, 'matchType': '历史名称匹配', 'base': '广东',
  'legalPersonName': '郑浩剑', 'estiblishTime': '2006-08-25 00:00:00.0', 'regCapital': '100000万人民币', 'regStatus': '存续',
  'score': '97', 'orginalScore': '9778', 'bonusScore': '0', 'companyScore': '97', 'historyNames': None,
  'categoryCode': '', 'industry': None,
  'humanNames': '刘雪琴\t:#0\t;\t周昭钦\t:#0\t;\t谢兰芳\t:#0\t;\t林海峰\t:#0\t;\t蒲海涛\t:#0\t;\t郑浩剑\t:#0\t;\t颜玲玲\t:#0\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None,
  'bondType': None, 'newtestName': None, 'regNumber': '440301103463379', 'orgNumber': '79258458-4',
  'creditCode': '91440300792584584M',
  'businessScope': '电子商务;电子支付;支付结算和清算系统的技术开发;计算机技术服务;计算机软;硬件的设计;技术开发;销售;数据库及计算机网络服务;国内商业;物资供销业;从事广告业务;在线数据处理与交易业务;信息服务业务;仅限互联网信息服务业务',
  'regLocation': '<em>深圳市</em>前海深港合作区前湾一路1号A栋201室（入驻<em>深圳市</em>前海商务秘书<em>有限公司</em>）；经营地址：<em>深圳市</em>南山区高新科技园科技中一路<em>腾讯</em>大厦8层。',
  'phone': '0755-86013388\t;\t07558601****', 'phoneList': ['0755-8601****'],
  'phoneInfoList': [{'number': '0755-86013388', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'}],
  'businessItemList': None, 'phoneNum': '0755-8601****',
  'logo': 'https://img5.tianyancha.com/logo/lll/23861417d97a33f8219e9e9fc76ba0ff.png@!f_200x200', 'city': '深圳市',
  'district': '南山区', 'emails': 'landyzhang@tencent.com', 'emailList': ['landyzhang@tencent.com'],
  'websites': 'https://www.fitgroup.com/\t;\twechatpay.cn\t;\twww.wisefx.com\t;\twww.iot-tencent.com.cn\t;\twww.zxgstock.com\t;\twww.tenpay.com\t;\twww.fatfreader.com\t;\twww.wisefx.cn\t;\twww.tenpay.cn',
  'hiddenPhones': None, 'abbr': '红包店\t:#1#\t;\t腾讯理财通\t:#1#\t;\t腾讯金融科技\t:#1#\t;\t财付通\t:#1#\t;\t', 'tagList': None,
  'companyType': 1, 'companyOrgType': '有限责任公司\t;\t有限责任公司', 'labelList': None,
  'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None, 'longitude': None,
  'legalPersonId': '2358780811', 'legalPersonType': '1', 'distance': None, 'categoryStr': '软件和信息技术服务业', 'isClaimed': 0,
  'claimPkgType': -2, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': '财付通', 'claimInfo': None,
  'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本', 'estiblishTimeShowStr': '成立日期',
  'multiMatchField': [{'isLink': 1, 'field': '历史名称', 'content': '<em>深圳市</em>财付通科技<em>有限公司</em>'},
                      {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'},
                      {'isLink': 1, 'field': '经营范围', 'content': '...的技术开发;<em>计算机</em>...及<em>计算机</em>...'}],
  'labelListV2': ['天使轮', '腾讯金融科技', '企业集团', '小微企业', '瞪羚企业', '曾用名', '高新技术企业'],
  'labelJsonList': ['{"type":1,"value":"天使轮"}', '{"type":1,"value":"腾讯金融科技"}', '{"type":1,"value":"企业集团"}',
                    '{"type":1,"value":"小微企业"}', '{"type":1,"value":"瞪羚企业"}', '{"type":1,"value":"曾用名"}',
                    '{"type":1,"value":"高新技术企业"}'], 'taxCode': '91440300792584584M', 'socialSecurityStaff_num': '1901',
  'categoryCodeStd': '651', 'hasMorePhone': None, 'hasVideo': None, 'videoId': None, 'isRecommend': None,
  'englishName': None, 'firstPositionShowStr': '法定代表人', 'secondPositionShowStr': '注册资本', 'firstPositionValue': '郑浩剑',
  'secondPositionValue': '100000万人民币', 'bizType': '7',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[0,0,0,4]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '100000.0', 'establish_time_long': '1156435200000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 1011, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 37108, 'historyRiskCount': 4, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': None, 'name': None, 'type': 1, 'matchType': None, 'base': None, 'legalPersonName': None, 'estiblishTime': '-',
  'regCapital': None, 'regStatus': None, 'score': None, 'orginalScore': None, 'bonusScore': None, 'companyScore': None,
  'historyNames': None, 'categoryCode': None, 'industry': None, 'humanNames': None, 'trademarks': None, 'tmList': None,
  'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None, 'bondType': None, 'newtestName': None,
  'regNumber': None, 'orgNumber': None, 'creditCode': None, 'businessScope': None, 'regLocation': None, 'phone': None,
  'phoneList': [], 'phoneInfoList': None, 'businessItemList': None, 'phoneNum': None, 'logo': None, 'city': None,
  'district': None, 'emails': None, 'emailList': None, 'websites': None, 'hiddenPhones': None, 'abbr': None,
  'tagList': None, 'companyType': None, 'companyOrgType': None, 'labelList': None, 'matchField': None, 'latitude': None,
  'longitude': None, 'legalPersonId': None, 'legalPersonType': None, 'distance': None, 'categoryStr': None,
  'isClaimed': None, 'claimPkgType': None, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': None,
  'claimInfo': None, 'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本',
  'estiblishTimeShowStr': '成立日期', 'multiMatchField': None, 'labelListV2': None, 'labelJsonList': None, 'taxCode': None,
  'socialSecurityStaff_num': None, 'categoryCodeStd': None, 'hasMorePhone': None, 'hasVideo': None, 'videoId': None,
  'isRecommend': None, 'englishName': None, 'firstPositionShowStr': None, 'secondPositionShowStr': None,
  'firstPositionValue': None, 'secondPositionValue': None, 'bizType': None, 'docFeature': None, 'contantMap': None,
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': None, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': None, 'historyRiskCount': None, 'followLabel': None, 'contentType': 8,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None,
  'brandInstitutionGroupCard': {'word': '深圳市腾讯计算机系统有限公司', 'count': 4, 'items': [
      {'id': 'b7f9b16382', 'name': '<em>腾讯</em>控股',
       'logo': 'https://img5.tianyancha.com/logo/product/67bd5df0a6358f7f1b1adfc6e32f23bc.png@!f_200x200',
       'alias': None,
       'intro': '腾讯成立于1998年11月，是目前中国领先的互联网综合服务提供商之一。成立10多年以来，腾讯一直秉承“一切以用户价值为依归”的经营理念，为亿级海量用户提供稳定优质的各类服务，始终处于稳健发展的状态。2004年6月16日，腾讯控股有限公司在香港联交所主板公开上市（股票代号00700）。',
       'base': '广东', 'setupDate': '1998-11-11', 'type': 1, 'companyName': '<em>深圳市腾讯计算机系统有限公司</em>', 'round': '战略融资',
       'competingCount': 0, 'eventCount': 0, 'fundCount': 0, 'graphId': 9519792, 'jingpinName': [], 'memberCount': None,
       'investCount': None, 'handelName': '', 'handelNameId': None, 'handelNameType': None, 'handelNameGroupId': 0,
       'roundCount': 6, 'investors': ['高瓴资本', 'IDG资本', '印尼力宝集团', '南非MIH米拉德国际控股集团公司', '香港盈科数码'],
       'actualControllerList': None, 'cardId': '163821'}, {'id': 'ba2bb2988', 'name': '<em>腾讯</em>投资',
                                                           'logo': 'https://img5.tianyancha.com/logo/jigou/1267e6c354602c1160fb12359871f980.png@!f_200x200',
                                                           'alias': None,
                                                           'intro': '腾讯投资成立于2008年，是腾讯集团的投资部门与核心战略部门之一，主导集团投资相关业务。长期专注于全球范围内消费互联网和产业互联网相关投资，聚焦文娱传媒、消费零售、民生教育、金融科技、企业服务及海外投资等领域，探索前沿创新与未来更多可能性。腾讯投资在过去十多年中总计投资800余家公司，包含百余家上市公司及独角兽企业，投资地域涵盖全球二十多个国家和地区，致力于发现为用户提供长期价值的创业者和企业，并帮助其成长。我们在北京、上海、深圳、香港都设有办公室，拥有一支超过60人的团队。',
                                                           'base': '深圳', 'setupDate': '2008-01-01', 'type': 2,
                                                           'companyName': '<em>深圳市腾讯计算机系统有限公司</em>', 'round': '',
                                                           'competingCount': 0, 'eventCount': 1516, 'fundCount': 12,
                                                           'graphId': 9519792, 'jingpinName': [], 'memberCount': None,
                                                           'investCount': None, 'handelName': '', 'handelNameId': None,
                                                           'handelNameType': None, 'handelNameGroupId': 0,
                                                           'roundCount': 0, 'investors': ['暂无'],
                                                           'actualControllerList': None, 'cardId': '29882'},
      {'id': 'b50aa274671', 'name': '<em>识</em>花君', 'logo': None, 'alias': None,
       'intro': '识花君是一款利用人工智能识别花草的小程序。3000多种常见花草，拍照上传，立刻识别。识花君还可以把你的照片制作成精美卡片，保存欣赏。', 'base': '广东',
       'setupDate': '1998-11-11', 'type': 1, 'companyName': '<em>深圳市腾讯计算机系统有限公司</em>', 'round': '战略融资',
       'competingCount': 0, 'eventCount': 0, 'fundCount': 0, 'graphId': 9519792, 'jingpinName': [], 'memberCount': None,
       'investCount': None, 'handelName': '', 'handelNameId': None, 'handelNameType': None, 'handelNameGroupId': 0,
       'roundCount': 6, 'investors': ['高瓴资本', 'IDG资本', '印尼力宝集团', '南非MIH米拉德国际控股集团公司', '香港盈科数码'],
       'actualControllerList': None, 'cardId': '2746711'},
      {'id': 'b3cb0312210', 'name': '微信发票助手', 'logo': None, 'alias': None,
       'intro': '微信发票小助手是一个能够快速开通和使用发票的小程序,通过二维码扫描即可快速开通发票。', 'base': '广东', 'setupDate': '1998-11-11', 'type': 1,
       'companyName': '<em>深圳市腾讯计算机系统有限公司</em>', 'round': '战略融资', 'competingCount': 0, 'eventCount': 0, 'fundCount': 0,
       'graphId': 9519792, 'jingpinName': [], 'memberCount': None, 'investCount': None, 'handelName': '',
       'handelNameId': None, 'handelNameType': None, 'handelNameGroupId': 0, 'roundCount': 6,
       'investors': ['高瓴资本', 'IDG资本', '印尼力宝集团', '南非MIH米拉德国际控股集团公司', '香港盈科数码'], 'actualControllerList': None,
       'cardId': '3122101'}]}, 'publishDemandCard': None, 'appDynamicCompanyCard': None},
 {'id': 1551867982, 'name': '众安在线财产保险股份<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '上海',
  'legalPersonName': '欧亚平', 'estiblishTime': '2013-10-09 00:00:00.0', 'regCapital': '146981.29万人民币', 'regStatus': '存续',
  'score': '98', 'orginalScore': '9827', 'bonusScore': '0', 'companyScore': '98', 'historyNames': None,
  'categoryCode': '', 'industry': None,
  'humanNames': '张爽\t:#0\t;\t欧亚平\t:#0\t;\t温玉萍\t:#0\t;\t姜兴\t:#0\t;\t欧晋羿\t:#0\t;\t陈慧\t:#0\t;\t杨楠\t:#0\t;\t李高峰\t:#0\t;\t史良洵\t:#0\t;\t张勇博\t:#0\t;\t王敏\t:#0\t;\t刘海姣\t:#0\t;\t欧伟\t:#0\t;\t邓锐民\t:#0\t;\t纪纲\t:#0\t;\t宋振华\t:#0\t;\t郭立民\t:#0\t;\t郑慧恩\t:#0\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': '众安在线',
  'bondNum': 'HK.06060', 'bondType': '港股', 'newtestName': None, 'regNumber': '310000000120842',
  'orgNumber': '08001368-7', 'creditCode': '91310000080013687R',
  'businessScope': '与互联网交易直接相关的企业;家庭财产保险;货运保险;责任保险;信用保证保险;短期健康;意外伤害保险;机动车保险;包括机动车交通事故责任强制保险和机动车商业保险;上述业务的再保险分出业务和再保险分入业务;仅限临时分保分入;法规允许的保险资金运用业务;保险信息服务业务;经中国保监会批准的其他业务',
  'regLocation': '上海市黄浦区圆明园路169号协进大楼4-5楼',
  'phone': '021-60278666\t;\t021-60278637\t;\t400-999-9595\t;\t02160278666\t;\t02160278637\t;\t400999****',
  'phoneList': ['021-6027****', '021-6027****', '400-999-****'],
  'phoneInfoList': [{'number': '021-60278666', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '021-60278637', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '400-999-9595', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'}],
  'businessItemList': None, 'phoneNum': '021-6027****',
  'logo': 'https://img5.tianyancha.com/logo/lll/e3b22f70de5fe0b8ae804db5d8ab987b.png@!f_200x200', 'city': '上海市',
  'district': '黄浦区', 'emails': 'cs@zhongan.com\t;\tzjb@zhongan.com', 'emailList': ['cs@zhongan.com', 'zjb@zhongan.com'],
  'websites': 'https://www.zhongan.com\t;\twww.zhongan.com\t;\twww.zacdn.cn\t;\twww.zas.ink\t;\twww.za.ink\t;\thttps://www.zhongan.com',
  'hiddenPhones': None, 'abbr': '众安在线\t:#1#\t;\t', 'tagList': None, 'companyType': 1,
  'companyOrgType': '股份有限公司\t;\t外商投资企业\t;\t股份有限公司(中外合资、上市)', 'labelList': None,
  'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None, 'longitude': None,
  'legalPersonId': '2025715293', 'legalPersonType': '1', 'distance': None, 'categoryStr': '保险业', 'isClaimed': 0,
  'claimPkgType': -2, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': '众安在线', 'claimInfo': None,
  'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本', 'estiblishTimeShowStr': '成立日期',
  'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}],
  'labelListV2': ['港股 | 正常上市', '中概股', '众安在线', '企业集团', '独角兽企业'], 'labelJsonList': [
     '{"bondType":"港股","listingStatus":"正常上市","bondNum":"HK.06060","sort":1,"type":2,"shortName":"众安在线","value":"港股 | 正常上市"}',
     '{"bondType":"中概股","listingStatus":"","bondNum":"ZZHGY","sort":2,"type":2,"shortName":"众安在线","value":"中概股"}',
     '{"type":1,"value":"众安在线"}', '{"type":1,"value":"企业集团"}', '{"type":1,"value":"独角兽企业"}'],
  'taxCode': '91310000080013687R', 'socialSecurityStaff_num': '1685', 'categoryCodeStd': '682', 'hasMorePhone': None,
  'hasVideo': None, 'videoId': None, 'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人',
  'secondPositionShowStr': '注册资本', 'firstPositionValue': '欧亚平', 'secondPositionValue': '146981.29万人民币', 'bizType': '8',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '146981.29', 'establish_time_long': '1381248000000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 13977, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 40116, 'historyRiskCount': 62, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 485687893, 'name': '<em>深圳市腾讯</em>网域<em>计算机</em>网络<em>有限公司</em>', 'type': 1, 'matchType': '历史名称匹配',
  'base': '广东', 'legalPersonName': '冯明杰', 'estiblishTime': '1997-04-28 00:00:00.0', 'regCapital': '1401000万人民币',
  'regStatus': '存续', 'score': '99', 'orginalScore': '9967', 'bonusScore': '0', 'companyScore': '99',
  'historyNames': None, 'categoryCode': '', 'industry': None,
  'humanNames': '周昭钦\t:#0\t;\t谢兰芳\t:#0\t;\t湛炜标\t:#0\t;\t冯明杰\t:#0\t;\t田丽\t:#0\t;\t', 'trademarks': None, 'tmList': None,
  'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None, 'bondType': None, 'newtestName': None,
  'regNumber': '440301103001006', 'orgNumber': '27933204-4', 'creditCode': '914403002793320449',
  'businessScope': '计算机软件技术开发;销售;网络商务;搜索引擎;网页制作;域名服务;行业信息;移动短信;网络游戏',
  'regLocation': '<em>深圳市</em>前海深港合作区前湾一路1号A栋201室（入驻<em>深圳市</em>前海商务秘书<em>有限公司</em>）',
  'phone': '0755-86013388\t;\t07558601****', 'phoneList': ['0755-8601****'],
  'phoneInfoList': [{'number': '0755-86013388', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'}],
  'businessItemList': None, 'phoneNum': '0755-8601****',
  'logo': 'https://img5.tianyancha.com/logo/lll/3f11e8836d790f14846acbf5953563d0.png@!f_200x200', 'city': '深圳市',
  'district': '南山区',
  'emails': 'adpm@tencent.com\t;\t2870979233@qq.com\t;\t240747163@qq.com\t;\tlandyzhang@tencent.com\t;\t2622618394@qq.com',
  'emailList': ['adpm@tencent.com', '2870979233@qq.com', '240747163@qq.com', 'landyzhang@tencent.com',
                '2622618394@qq.com'], 'websites': '', 'hiddenPhones': None, 'abbr': '网域游戏平台\t:#1#\t;\t腾讯投资\t:#2#\t;\t',
  'tagList': None, 'companyType': 1, 'companyOrgType': '有限责任公司\t;\t有限责任公司', 'labelList': None,
  'matchField': {'field': '历史名称', 'content': '<em>深圳市</em>网域<em>计算机</em>网络<em>有限公司</em>'}, 'latitude': None,
  'longitude': None, 'legalPersonId': '1801776421', 'legalPersonType': '1', 'distance': None, 'categoryStr': '互联网和相关服务',
  'isClaimed': 0, 'claimPkgType': -2, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': '腾讯网域',
  'claimInfo': None, 'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本',
  'estiblishTimeShowStr': '成立日期',
  'multiMatchField': [{'isLink': 1, 'field': '历史名称', 'content': '<em>深圳市</em>网域<em>计算机</em>网络<em>有限公司</em>'},
                      {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'},
                      {'isLink': 1, 'field': '经营范围', 'content': '<em>计算机</em>软件技术开发;销售;网络商...'}],
  'labelListV2': ['网域游戏平台', '投资机构', '企业集团', '小微企业', '曾用名', '高新技术企业'],
  'labelJsonList': ['{"type":1,"value":"网域游戏平台"}', '{"type":1,"value":"投资机构"}', '{"type":1,"value":"企业集团"}',
                    '{"type":1,"value":"小微企业"}', '{"type":1,"value":"曾用名"}', '{"type":1,"value":"高新技术企业"}'],
  'taxCode': '914403002793320449', 'socialSecurityStaff_num': '79', 'categoryCodeStd': '651', 'hasMorePhone': None,
  'hasVideo': None, 'videoId': None, 'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人',
  'secondPositionShowStr': '注册资本', 'firstPositionValue': '冯明杰', 'secondPositionValue': '1401000万人民币', 'bizType': '7',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[0,0,0,6]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '1401000.0', 'establish_time_long': '862156800000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 22, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 63806, 'historyRiskCount': 0, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 3450971002, 'name': '<em>深圳</em>高灯<em>计算机</em>科技<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '广东',
  'legalPersonName': '张民遐', 'estiblishTime': '2017-05-05 00:00:00.0', 'regCapital': '945.518891万人民币', 'regStatus': '存续',
  'score': '70', 'orginalScore': '6909', 'bonusScore': '1', 'companyScore': '69', 'historyNames': None,
  'categoryCode': '', 'industry': None,
  'humanNames': 'GAOGORDONXIA\t:#0\t;\t张民遐\t:#0\t;\t权铮\t:#0\t;\t李岩\t:#0\t;\t李迪\t:#0\t;\t林峰\t:#0\t;\t梁宇鹏\t:#0\t;\t王明宇\t:#0\t;\t王红卫\t:#0\t;\t胡丽丽\t:#0\t;\t莫晓盛\t:#0\t;\t蒋国英\t:#0\t;\t韩莹\t:#0\t;\t黄立明\t:#0\t;\t李迪\t:#1\t;\t莫晓盛\t:#1\t;\t金超\t:#1\t;\t张民遐\t:#1\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None,
  'bondType': None, 'newtestName': None, 'regNumber': '', 'orgNumber': 'MA5RH09M-0', 'creditCode': '91469027MA5RH09M0R',
  'businessScope': '信息系统集成服务;信息技术咨询服务;信息技术外包;电子商务平台建设;信息技术服务;从事广告业务;企业财务管理咨询;财务信息咨询;企业管理咨询;商务信息咨询;数据处理服务;计算机软件开发;经济信息咨询;代订酒店客房;车船票;飞机票;景点门票;旅游套票;餐饮;数字积分管理系统的技术开发;商业消费积分管理;积分兑换服务;计算机软件;信息系统软件的技术开发与销售;IT;信息技术;人才培训;智能终端的研发和制造;电信增值业务',
  'regLocation': '深圳市南山区粤海街道大冲社区深南大道9678号大冲商务中心(二期)1栋2号楼27D', 'phone': '0755-86237080\t;\t07558623****',
  'phoneList': ['0755-8623****'],
  'phoneInfoList': [{'number': '0755-86237080', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'}],
  'businessItemList': None, 'phoneNum': '0755-8623****',
  'logo': 'https://img5.tianyancha.com/logo/lll/62a49335c9eb62b0d31a0593de44f74a.png@!f_200x200', 'city': '深圳市',
  'district': '宝安区', 'emails': 'golden@wetax.com.cn\t;\tgolden@goldentec.com',
  'emailList': ['golden@wetax.com.cn', 'golden@goldentec.com'],
  'websites': 'https://www.wetax.com.cn\t;\twww.goldentec.com\t;\twww.wetax.com.cn\t;\tgolcer.cn\t;\twww.fapiao123.com\t;\twww.yunpiaoer.com\t;\twww.golcer.com\t;\twww.yunpiaoer.cn\t;\thttps://www.goldentec.com',
  'hiddenPhones': None, 'abbr': '高灯科技\t:#1#\t;\t', 'tagList': None, 'companyType': 1,
  'companyOrgType': '有限责任公司\t;\t其他有限责任公司', 'labelList': None,
  'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None, 'longitude': None,
  'legalPersonId': '1928381412', 'legalPersonType': '1', 'distance': None, 'categoryStr': '软件和信息技术服务业', 'isClaimed': 0,
  'claimPkgType': -1, 'realClaimPkgType': -1, 'baiduUrl': None, 'isBranch': 0, 'alias': '高灯', 'claimInfo': None,
  'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本', 'estiblishTimeShowStr': '成立日期',
  'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'},
                      {'isLink': 1, 'field': '经营范围', 'content': '...成服...;<em>计算机</em>...;<em>计算机</em>...'}],
  'labelListV2': ['B轮', '高灯科技', '企业集团', '高新技术企业', '曾用名'],
  'labelJsonList': ['{"type":1,"value":"B轮"}', '{"type":1,"value":"高灯科技"}', '{"type":1,"value":"企业集团"}',
                    '{"type":1,"value":"高新技术企业"}', '{"type":1,"value":"曾用名"}'], 'taxCode': '91469027MA5RH09M0R',
  'socialSecurityStaff_num': '0', 'categoryCodeStd': '652', 'hasMorePhone': None, 'hasVideo': None, 'videoId': None,
  'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人', 'secondPositionShowStr': '注册资本',
  'firstPositionValue': '张民遐', 'secondPositionValue': '945.518891万人民币', 'bizType': '7',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '945.518891', 'establish_time_long': '1493913600000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 13, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 37091, 'historyRiskCount': 8, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': None, 'name': None, 'type': 1, 'matchType': None, 'base': None, 'legalPersonName': None, 'estiblishTime': '-',
  'regCapital': None, 'regStatus': None, 'score': None, 'orginalScore': None, 'bonusScore': None, 'companyScore': None,
  'historyNames': None, 'categoryCode': None, 'industry': None, 'humanNames': None, 'trademarks': None, 'tmList': None,
  'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None, 'bondType': None, 'newtestName': None,
  'regNumber': None, 'orgNumber': None, 'creditCode': None, 'businessScope': None, 'regLocation': None, 'phone': None,
  'phoneList': [], 'phoneInfoList': None, 'businessItemList': None, 'phoneNum': None, 'logo': None, 'city': None,
  'district': None, 'emails': None, 'emailList': None, 'websites': None, 'hiddenPhones': None, 'abbr': None,
  'tagList': None, 'companyType': None, 'companyOrgType': None, 'labelList': None, 'matchField': None, 'latitude': None,
  'longitude': None, 'legalPersonId': None, 'legalPersonType': None, 'distance': None, 'categoryStr': None,
  'isClaimed': None, 'claimPkgType': None, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': None,
  'claimInfo': None, 'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本',
  'estiblishTimeShowStr': '成立日期', 'multiMatchField': None, 'labelListV2': None, 'labelJsonList': None, 'taxCode': None,
  'socialSecurityStaff_num': None, 'categoryCodeStd': None, 'hasMorePhone': None, 'hasVideo': None, 'videoId': None,
  'isRecommend': None, 'englishName': None, 'firstPositionShowStr': None, 'secondPositionShowStr': None,
  'firstPositionValue': None, 'secondPositionValue': None, 'bizType': None, 'docFeature': None, 'contantMap': None,
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': None, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': None, 'historyRiskCount': None, 'followLabel': None, 'contentType': 2,
  'normalWord': '深圳市腾讯计算机系统有限公司',
  'suggestWordList': ['深圳市腾讯 马化腾', '深圳市腾讯集团', '腾竞体育', '深圳市腾讯信息', '腾讯物联网服务平台', '深圳市腾讯产业投资', '零水日', '联盟大陆', '识花君',
                      '深圳市腾讯信达', '王者荣耀', '深圳市腾讯产业创投'], 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 3224489386, 'name': '益盟股份<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '上海',
  'legalPersonName': '曾山', 'estiblishTime': '2005-12-23 00:00:00.0', 'regCapital': '44300万人民币', 'regStatus': '存续',
  'score': '96', 'orginalScore': '9523', 'bonusScore': '1', 'companyScore': '95', 'historyNames': None,
  'categoryCode': '', 'industry': None,
  'humanNames': '俞湧\t:#0\t;\t束建平\t:#0\t;\t曾山\t:#0\t;\t李晓东\t:#0\t;\t张苏\t:#0\t;\t郭斐\t:#0\t;\t刘杉\t:#0\t;\t湛炜标\t:#0\t;\t郭春梅\t:#0\t;\t王晓阳\t:#0\t;\t赵华\t:#0\t;\t杨军\t:#0\t;\t曾山\t:#1\t;\t周立宸\t:#1\t;\t李立钧\t:#1\t;\t李曙光\t:#1\t;\t朱雯华\t:#1\t;\t伍志广\t:#1\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': '益盟股份',
  'bondNum': '832950', 'bondType': '新三板', 'newtestName': None, 'regNumber': '310115000930219',
  'orgNumber': '78426190-2', 'creditCode': '91310000784261902Q',
  'businessScope': '第二类增值电信业务;计算机软件的开发;设计;制作;销售自产产品;提供上述相关产品;电子信息;计算机;网络工程领域内的;服务;证券投资咨询;商务咨询;投资咨询;经济信息咨询;凭营业执照依法自主开展经营活动',
  'regLocation': '上海市徐汇区中山西路2020号503A1室',
  'phone': '021-61958874\t;\t021-61958888\t;\t021-61958820\t;\t02161958874\t;\t02161958888\t;\t0216195****',
  'phoneList': ['021-6195****', '021-6195****', '021-6195****'],
  'phoneInfoList': [{'number': '021-61958874', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '021-61958888', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '021-61958820', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'}],
  'businessItemList': None, 'phoneNum': '021-6195****',
  'logo': 'https://img5.tianyancha.com/logo/lll/174e7015f9cdb7f845ebe748867c96a1.png@!f_200x200', 'city': '上海市',
  'district': '徐汇区', 'emails': 'tanfei@emoney.cn\t;\tyangkaidi@emoney.cn\t;\tyanlu@emoney.cn',
  'emailList': ['tanfei@emoney.cn', 'yangkaidi@emoney.cn', 'yanlu@emoney.cn'],
  'websites': 'http://www.emoney.cn\t;\twww.newistock.com\t;\twww.etoujiao.com\t;\twww.emstock.com.cn',
  'hiddenPhones': None, 'abbr': '益盟操盘手\t:#1#\t;\t益盟股份\t:#1#\t;\t', 'tagList': None, 'companyType': 1,
  'companyOrgType': '股份有限公司\t;\t股份有限公司(非上市、自然人投资或控股)', 'labelList': None,
  'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None, 'longitude': None,
  'legalPersonId': '1968583732', 'legalPersonType': '1', 'distance': None, 'categoryStr': '软件和信息技术服务业', 'isClaimed': 0,
  'claimPkgType': 0, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': '益盟股份', 'claimInfo': None,
  'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本', 'estiblishTimeShowStr': '成立日期',
  'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'},
                      {'isLink': 1, 'field': '经营范围', 'content': '...业务;<em>计算机</em>软件的...'}],
  'labelListV2': ['定向增发', '新三板 | 正常上市', '益盟股份', '企业集团', '曾用名', '高新技术企业', '瞪羚企业'],
  'labelJsonList': ['{"type":1,"value":"定向增发"}',
                    '{"bondType":"新三板","listingStatus":"正常上市","bondNum":"832950","sort":1,"type":2,"shortName":"益盟股份","value":"新三板 | 正常上市"}',
                    '{"type":1,"value":"益盟股份"}', '{"type":1,"value":"企业集团"}', '{"type":1,"value":"曾用名"}',
                    '{"type":1,"value":"高新技术企业"}', '{"type":1,"value":"瞪羚企业"}'], 'taxCode': '91310000784261902Q',
  'socialSecurityStaff_num': '1107', 'categoryCodeStd': '651', 'hasMorePhone': None, 'hasVideo': None, 'videoId': None,
  'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人', 'secondPositionShowStr': '注册资本',
  'firstPositionValue': '曾山', 'secondPositionValue': '44300万人民币', 'bizType': '8',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '44300.0', 'establish_time_long': '1135267200000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 45, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 39144, 'historyRiskCount': 2, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 274940180, 'name': '未来电视<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '天津', 'legalPersonName': '李鸣',
  'estiblishTime': '2011-12-02 00:00:00.0', 'regCapital': '20000万人民币', 'regStatus': '存续', 'score': '93',
  'orginalScore': '9262', 'bonusScore': '1', 'companyScore': '92', 'historyNames': None, 'categoryCode': '',
  'industry': None,
  'humanNames': '李鸣\t:#0\t;\t王雪飞\t:#0\t;\t韦宁\t:#0\t;\t侯立民\t:#0\t;\t徐长军\t:#0\t;\t孙忠怀\t:#0\t;\t王冰松\t:#0\t;\t刘群\t:#0\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None,
  'bondType': None, 'newtestName': None, 'regNumber': '120116000079892', 'orgNumber': '58641988-7',
  'creditCode': '91120116586419887T',
  'businessScope': '信息网络传播视听节目;网络文化经营;互联网信息服务;第二类增值电信业务;广播电视节目制作经营;广播电视视频点播业务;出版物零售;出版物互联网销售;电子出版物制作;音像制品制作;电视剧制作;电视剧发行;电影发行;演出经纪;食品互联网销售;食品销售;药品零售;药品互联网信息服务;医疗器械互联网信息服务;互联网销售;国内贸易代理;销售代理;第二类医疗器械销售;医用口罩零售;汽车零配件零售;汽车装饰用品销售;新能源汽车整车销售;汽车销售;工艺美术品及收藏品零售;新鲜蔬菜批发;集成电路芯片及产品销售;显示器件销售;技术服务;技术开发;技术咨询;技术交流;技术转让;技术推广;软件外包服务;软件开发;动漫游戏开发;家用视听设备销售;办公用品销售;玩具;动漫及游艺用品销售;家用电器销售;家用电器零配件销售;日用化学产品销售;日用百货销售;照相机及器材销售;办公设备销售;针纺织品及原料销售;化妆品零售;广播影视设备销售;电影摄制服务;广告制作;广告设计;代理;版权代理;广告发布;旅行社服务网点旅游招徕;咨询服务;信息咨询服务;专业设计服务;摄像及视频制作服务;互联网数据服务;物业管理;信息技术咨询服务;宠物食品及用品零售;宠物食品及用品批发;金银制品销售;货物进出口;进出口代理;普通货物仓储服务;进出口商品检验鉴定;环保咨询服务;在保险公司授权范围内开展专属保险代理业务;凭授权经营;汽车零配件批发;凭营业执照依法自主开展经营活动',
  'regLocation': '天津市东丽区天津自贸试验区（空港经济区）环河北路80号空港商务园东区5-1，2-501', 'phone': '1862262****', 'phoneList': ['1862262****'],
  'phoneInfoList': [{'number': '18622624328', 'type': '1', 'source': None, 'comment': '号码可正常联系'}],
  'businessItemList': None, 'phoneNum': '1862262****',
  'logo': 'https://img5.tianyancha.com/logo/lll/8ded1a7ea2405b1f9baed8d9983a2e3b.png@!fill_200x200', 'city': '天津市',
  'district': '静海区', 'emails': 'yu.huiran@chinaott.net', 'emailList': ['yu.huiran@chinaott.net'],
  'websites': 'www.chinaott.net', 'hiddenPhones': None, 'abbr': '未来电视\t:#1#\t;\t', 'tagList': None, 'companyType': 1,
  'companyOrgType': '有限责任公司\t;\t有限责任公司', 'labelList': None,
  'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None, 'longitude': None,
  'legalPersonId': '2344061169', 'legalPersonType': '1', 'distance': None, 'categoryStr': '计算机、通信和其他电子设备制造业',
  'isClaimed': 0, 'claimPkgType': -1, 'realClaimPkgType': -1, 'baiduUrl': None, 'isBranch': 0, 'alias': '未来电视',
  'claimInfo': None, 'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本',
  'estiblishTimeShowStr': '成立日期', 'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}],
  'labelListV2': ['A轮', '未来电视', '企业集团', '曾用名', '高新技术企业', '专精特新'],
  'labelJsonList': ['{"type":1,"value":"A轮"}', '{"type":1,"value":"未来电视"}', '{"type":1,"value":"企业集团"}',
                    '{"type":1,"value":"曾用名"}', '{"type":1,"value":"高新技术企业"}', '{"type":1,"value":"专精特新"}'],
  'taxCode': '91120116586419887T', 'socialSecurityStaff_num': '570', 'categoryCodeStd': '393', 'hasMorePhone': None,
  'hasVideo': None, 'videoId': None, 'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人',
  'secondPositionShowStr': '注册资本', 'firstPositionValue': '李鸣', 'secondPositionValue': '20000万人民币', 'bizType': '7',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '20000.0', 'establish_time_long': '1322755200000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 10092, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 39693, 'historyRiskCount': 240, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 9519784, 'name': '北京搜狗信息服务<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '北京',
  'legalPersonName': '叶骏', 'estiblishTime': '2005-12-28 00:00:00.0', 'regCapital': '2000万人民币', 'regStatus': '存续',
  'score': '77', 'orginalScore': '7739', 'bonusScore': '0', 'companyScore': '77', 'historyNames': None,
  'categoryCode': '', 'industry': None, 'humanNames': '叶骏\t:#0\t;\t鲁剑\t:#0\t;\t邓晓燕\t:#0\t;\t金园园\t:#0\t;\t刁云芸\t:#0\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': '搜狗', 'bondNum': 'SOGO',
  'bondType': '中概股', 'newtestName': None, 'regNumber': '110108009232616', 'orgNumber': '78397331-8',
  'creditCode': '91110108783973318P',
  'businessScope': '互联网地图服务;甲级;利用信息网络经营音乐娱乐产品;演出剧;节;目;表演;动漫产品;从事网络文化产品的展览;比赛活动;游戏产品;含网络游戏虚拟货币发行;第二类增值电信业务中的信息服务业务;仅限互联网信息服务;增值电信业务;互联网药品信息服务;以互联网药品信息服务资格证书为准;销售食品;技术开发;技术咨询;技术服务;技术转让;火车票销售代理;文艺演出票务代理;体育赛事票务代理;数据处理;数据处理中的银行卡中心;PUE值在1;5以上的云计算数据中心除外;软件开发;基础软件服务;电脑动画设计;产品设计;经济贸易咨询;销售文化用品;日用品;礼品;针纺织品;服装;体育用品;机械设备;五金交电;电子产品;计算机;软件及辅助设备;家用电器;电话充值卡;医疗器械I类;出版物批发;广播电视节目制作;销售食品以及依法须经批准的项目',
  'regLocation': '北京市海淀区西北旺东路10号院西区9号楼3层101',
  'phone': '010-56899999\t;\t010-86899999\t;\t010-62726666\t;\t01056899999\t;\t01086899999\t;\t0106272****',
  'phoneList': ['010-5689****', '010-8689****', '010-6272****'],
  'phoneInfoList': [{'number': '010-56899999', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '010-86899999', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '010-62726666', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'}],
  'businessItemList': None, 'phoneNum': '010-5689****',
  'logo': 'https://img5.tianyancha.com/logo/lll/fc6ca949108930c923a41be776003458.png@!f_200x200', 'city': '北京市',
  'district': '海淀区', 'emails': 'info@sogou-inc.com\t;\tjianyitousu@sogou-inc.com\t;\tliuruiqing@sogou-inc.com',
  'emailList': ['info@sogou-inc.com', 'jianyitousu@sogou-inc.com', 'liuruiqing@sogou-inc.com'],
  'websites': 'sogou.net\t;\tsogo.com\t;\tsogoucdn.com\t;\tggowan.com\t;\tyeyousg.com\t;\twww.xiangrikuijianzhan.com\t;\twww.qd.ink\t;\twww.sogou.com\t;\twww.imancheng.cn\t;\tsogou-inc.com',
  'hiddenPhones': None, 'abbr': '搜狗略懂\t:#1#\t;\t糖猫\t:#1#\t;\t', 'tagList': None, 'companyType': 1,
  'companyOrgType': '有限责任公司\t;\t其他有限责任公司', 'labelList': None,
  'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None, 'longitude': None,
  'legalPersonId': '1836461422', 'legalPersonType': '1', 'distance': None, 'categoryStr': '科技推广和应用服务业', 'isClaimed': 0,
  'claimPkgType': None, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': '搜狗信息', 'claimInfo': None,
  'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本', 'estiblishTimeShowStr': '成立日期',
  'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'},
                      {'isLink': 1, 'field': '经营范围', 'content': '...电;电子产品;<em>计算机</em>;软件及辅助...'}],
  'labelListV2': ['中概股', '糖猫', '企业集团', '独角兽企业', '小微企业', '高新技术企业', '瞪羚企业'], 'labelJsonList': [
     '{"bondType":"中概股","listingStatus":"","bondNum":"SOGO","sort":1,"type":2,"shortName":"搜狗","value":"中概股"}',
     '{"type":1,"value":"糖猫"}', '{"type":1,"value":"企业集团"}', '{"type":1,"value":"独角兽企业"}', '{"type":1,"value":"小微企业"}',
     '{"type":1,"value":"高新技术企业"}', '{"type":1,"value":"瞪羚企业"}'], 'taxCode': '91110108783973318P',
  'socialSecurityStaff_num': '41', 'categoryCodeStd': '642', 'hasMorePhone': None, 'hasVideo': None, 'videoId': None,
  'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人', 'secondPositionShowStr': '注册资本',
  'firstPositionValue': '叶骏', 'secondPositionValue': '2000万人民币', 'bizType': '7',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '2000.0', 'establish_time_long': '1135699200000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 1636, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 37187, 'historyRiskCount': 32, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 3208361333, 'name': '国铁吉讯科技<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '北京',
  'legalPersonName': '马建军', 'estiblishTime': '2017-12-20 00:00:00.0', 'regCapital': '25000万人民币', 'regStatus': '存续',
  'score': '93', 'orginalScore': '9328', 'bonusScore': '0', 'companyScore': '93', 'historyNames': None,
  'categoryCode': '', 'industry': None,
  'humanNames': '潘鲲\t:#0\t;\t张成\t:#0\t;\t丁珂\t:#0\t;\t王忠峰\t:#0\t;\t马建军\t:#0\t;\t魏志玲\t:#0\t;\t汪红飞\t:#0\t;\t朱建生\t:#0\t;\t孙宏\t:#0\t;\t李佳宁\t:#0\t;\t王富章\t:#0\t;\t武斌\t:#1\t;\t王满华\t:#1\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None,
  'bondType': None, 'newtestName': None, 'regNumber': '110108024617656', 'orgNumber': 'MA019FDM0',
  'creditCode': '91110108MA019FDM0E',
  'businessScope': '技术服务;技术开发;技术推广;技术咨询;技术转让;设计;制作;代理;发布广告;基础软件服务;应用软件服务;软件开发;计算机系统服务;数据处理;数据处理中的银行卡中心;PUE值在1;5以上的云计算数据中心除外;软件咨询;产品设计;公园门票销售代理;文艺演出门票销售代理;酒店管理;企业管理咨询;经济贸易咨询;运输代理服务;汽车租赁;机动车公共停车场服务;生产无线通信设备;限在外埠从事生产经营活动;销售日用品;服装;鞋帽;皮革制品;玩具;洗涤用品;化妆品;护肤用品;摄影器材;音响设备及器材;体育用品;文化用品;办公设备;包装材料;工艺品;礼品;首饰;化工产品;五金交电;汽车零配件;摩托车零配件;电子产品;通讯设备;仪器仪表;机械设备;计算机;软件及辅助设备;塑料制品;橡胶制品;金属制品;玻璃制品;建筑材料;金属材料;装饰材料;食用农产品;家具;针纺织品;化肥;医疗器械I类;II类;仓储服务;铁路客运票务代理服务;旅客联运票务代理服务;餐饮服务;装卸服务;信息系统集成服务;工程勘察;工程设计;专业承包;维修机械设备;国内货物运输代理;商务代理代办服务;货物进出口;网络预约出租汽车经营;从事互联网文化活动;互联网信息服务;出版物零售;保险代理业务;销售食品;道路货物运输;广播电视节目制作;经营电信业务',
  'regLocation': '北京市海淀区大柳树路2号一区12幢2层213-216', 'phone': '15088778340\t;\t18693196919\t;\t010-51876106\t;\t0105187****',
  'phoneList': ['1508877****', '1869319****', '010-5187****'],
  'phoneInfoList': [{'number': '15088778340', 'type': '1', 'source': None, 'comment': '号码可正常联系'},
                    {'number': '18693196919', 'type': '1', 'source': None, 'comment': '号码可正常联系'},
                    {'number': '010-51876106', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'}],
  'businessItemList': None, 'phoneNum': '1508877****',
  'logo': 'https://img5.tianyancha.com/logo/lll/caf23e642d653d775f28dd96a4b583a6.png@!f_200x200', 'city': '北京市',
  'district': '海淀区', 'emails': 'public@crgecent.com\t;\tmia.li@crgecent.com\t;\t123456@qq.com',
  'emailList': ['public@crgecent.com', 'mia.li@crgecent.com', '123456@qq.com'],
  'websites': 'www.crgecent.com\t;\tcrgt.xyz\t;\tcrgtt.cn\t;\tcrgtt.net\t;\tcrgt.info\t;\twww.ccrgt.com\t;\twww.crgtt.com\t;\twww.jinluos.com\t;\twww.jinlu-wl.com\t;\twww.wmlaas.com\t;\twww.crgt.net.cn',
  'hiddenPhones': None, 'abbr': '国铁吉讯\t:#1#\t;\t', 'tagList': None, 'companyType': 1,
  'companyOrgType': '有限责任公司\t;\t其他有限责任公司', 'labelList': None,
  'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None, 'longitude': None,
  'legalPersonId': '2278987557', 'legalPersonType': '1', 'distance': None, 'categoryStr': '科技推广和应用服务业', 'isClaimed': 0,
  'claimPkgType': None, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': '国铁吉讯', 'claimInfo': None,
  'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本', 'estiblishTimeShowStr': '成立日期',
  'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'},
                      {'isLink': 1, 'field': '经营范围', 'content': '...开发;<em>计算机系统</em>服务;....'}],
  'labelListV2': ['股权融资', '国铁吉讯', '企业集团', '曾用名', '高新技术企业', '独角兽企业'],
  'labelJsonList': ['{"type":1,"value":"股权融资"}', '{"type":1,"value":"国铁吉讯"}', '{"type":1,"value":"企业集团"}',
                    '{"type":1,"value":"曾用名"}', '{"type":1,"value":"高新技术企业"}', '{"type":1,"value":"独角兽企业"}'],
  'taxCode': '91110108MA019FDM0E', 'socialSecurityStaff_num': '75', 'categoryCodeStd': '751', 'hasMorePhone': None,
  'hasVideo': None, 'videoId': None, 'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人',
  'secondPositionShowStr': '注册资本', 'firstPositionValue': '马建军', 'secondPositionValue': '25000万人民币', 'bizType': '7',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '25000.0', 'establish_time_long': '1513699200000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 18, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 37758, 'historyRiskCount': 0, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 2347249922, 'name': '<em>腾讯</em>征信<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '广东',
  'legalPersonName': '林海峰', 'estiblishTime': '2015-03-17 00:00:00.0', 'regCapital': '5000万人民币', 'regStatus': '存续',
  'score': '83', 'orginalScore': '8365', 'bonusScore': '0', 'companyScore': '83', 'historyNames': None,
  'categoryCode': '', 'industry': None, 'humanNames': '郑浩剑\t:#0\t;\t刘华\t:#0\t;\t林海峰\t:#0\t;\t冯明杰\t:#0\t;\t田丽\t:#0\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None,
  'bondType': None, 'newtestName': None, 'regNumber': '440301112367499', 'orgNumber': '33518706-5',
  'creditCode': '91440300335187065E', 'businessScope': '为机构用户提供信用信息支持;企业征信及相关业务;市场信息咨询;投资咨询;技术服务',
  'regLocation': '深圳市前海深港合作区前湾一路1号A栋201室（入驻深圳市前海商务秘书有限公司）（经营场所：深圳市南山区高新园科技中一路腾讯大厦11楼东）',
  'phone': '0755-86013388\t;\t07558601****', 'phoneList': ['0755-8601****'],
  'phoneInfoList': [{'number': '0755-86013388', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'}],
  'businessItemList': None, 'phoneNum': '0755-8601****',
  'logo': 'https://img5.tianyancha.com/logo/lll/286d0a043c6f9ebd1b1f797df5e14d2b.png@!f_200x200', 'city': '深圳市',
  'district': '南山区', 'emails': 'adpm@tencent.com\t;\t2870979233@qq.com\t;\t240747163@qq.com\t;\tlandyzhang@tencent.com',
  'emailList': ['adpm@tencent.com', '2870979233@qq.com', '240747163@qq.com', 'landyzhang@tencent.com'],
  'websites': 'www.xinyong.com.cn', 'hiddenPhones': None, 'abbr': '腾讯信用\t:#1#\t;\t腾讯投资\t:#2#\t;\t', 'tagList': None,
  'companyType': 1, 'companyOrgType': '有限责任公司\t;\t有限责任公司', 'labelList': None,
  'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None, 'longitude': None,
  'legalPersonId': '2010460613', 'legalPersonType': '1', 'distance': None, 'categoryStr': '商务服务业', 'isClaimed': 0,
  'claimPkgType': -2, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': '腾讯征信', 'claimInfo': None,
  'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本', 'estiblishTimeShowStr': '成立日期',
  'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}],
  'labelListV2': ['腾讯信用', '投资机构', '企业集团', '小微企业'],
  'labelJsonList': ['{"type":1,"value":"腾讯信用"}', '{"type":1,"value":"投资机构"}', '{"type":1,"value":"企业集团"}',
                    '{"type":1,"value":"小微企业"}'], 'taxCode': '91440300335187065E', 'socialSecurityStaff_num': '9',
  'categoryCodeStd': '721', 'hasMorePhone': None, 'hasVideo': None, 'videoId': None, 'isRecommend': None,
  'englishName': None, 'firstPositionShowStr': '法定代表人', 'secondPositionShowStr': '注册资本', 'firstPositionValue': '林海峰',
  'secondPositionValue': '5000万人民币', 'bizType': '7',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '5000.0', 'establish_time_long': '1426521600000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 0, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 37102, 'historyRiskCount': 0, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 472146652, 'name': '广州银汉科技<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '广东',
  'legalPersonName': '刘泳', 'estiblishTime': '2001-11-15 00:00:00.0', 'regCapital': '1194.7431万人民币', 'regStatus': '存续',
  'score': '74', 'orginalScore': '7408', 'bonusScore': '0', 'companyScore': '74', 'historyNames': None,
  'categoryCode': '', 'industry': None,
  'humanNames': 'LUPENG\t:#0\t;\t刘泳\t:#0\t;\t王夫也\t:#0\t;\t苏龙德\t:#0\t;\t邝小翚\t:#0\t;\t钟林\t:#0\t;\t陈璐瑶\t:#0\t;\t马立欢\t:#0\t;\t冷美华\t:#1\t;\t刘泳\t:#1\t;\t刘长菊\t:#1\t;\t苏龙德\t:#1\t;\t钟林\t:#1\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None,
  'bondType': None, 'newtestName': None, 'regNumber': '440106000362969', 'orgNumber': '73295632-3',
  'creditCode': '91440115732956323K', 'businessScope': '游戏设计制作;软件开发;网络技术的研究;开发;计算机技术开发;技术服务;信息技术咨询服务;增值电信服务;网络游戏服务',
  'regLocation': '广州市天河区黄埔大道中666号701房（仅限办公）', 'phone': '020-85562666\t;\t020-87569366\t;\t02085562666\t;\t0208756****',
  'phoneList': ['020-8556****', '020-8756****'],
  'phoneInfoList': [{'number': '020-85562666', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '020-87569366', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'}],
  'businessItemList': None, 'phoneNum': '020-8556****',
  'logo': 'https://img5.tianyancha.com/logo/lll/06ae80721123ba804bdd9e6598b6a3d2.png@!f_200x200', 'city': '广州市',
  'district': '天河区', 'emails': 'mail@yh.cn\t;\txusui@yh.cn\t;\txusui@01234.com.cn',
  'emailList': ['mail@yh.cn', 'xusui@yh.cn', 'xusui@01234.com.cn'],
  'websites': 'www.01234.com.cn\t;\twww.yh.cn\t;\twww.egege.com.cn\t;\twww.yhres.cn', 'hiddenPhones': None,
  'abbr': '银汉游戏\t:#1#\t;\t银汉科技\t:#1#\t;\t', 'tagList': None, 'companyType': 1, 'companyOrgType': '有限责任公司\t;\t其他有限责任公司',
  'labelList': None, 'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None,
  'longitude': None, 'legalPersonId': '1813830269', 'legalPersonType': '1', 'distance': None, 'categoryStr': '研究和试验发展',
  'isClaimed': 0, 'claimPkgType': None, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': '银汉科技',
  'claimInfo': None, 'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本',
  'estiblishTimeShowStr': '成立日期', 'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'},
                                                      {'isLink': 1, 'field': '经营范围',
                                                       'content': '...的研究;开发;<em>计算机</em>技术开发;技...'}],
  'labelListV2': ['并购', '银汉科技', '企业集团', '高新技术企业', '瞪羚企业'],
  'labelJsonList': ['{"type":1,"value":"并购"}', '{"type":1,"value":"银汉科技"}', '{"type":1,"value":"企业集团"}',
                    '{"type":1,"value":"高新技术企业"}', '{"type":1,"value":"瞪羚企业"}'], 'taxCode': '91440115732956323K',
  'socialSecurityStaff_num': '255', 'categoryCodeStd': '653', 'hasMorePhone': None, 'hasVideo': None, 'videoId': None,
  'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人', 'secondPositionShowStr': '注册资本',
  'firstPositionValue': '刘泳', 'secondPositionValue': '1194.7431万人民币', 'bizType': '7',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '1194.7431', 'establish_time_long': '1005753600000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 25, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 37648, 'historyRiskCount': 3, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 3090199111, 'name': '<em>腾讯</em>大地通途（北京）科技<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '北京',
  'legalPersonName': '钟翔平', 'estiblishTime': '2005-02-03 00:00:00.0', 'regCapital': '6000万人民币', 'regStatus': '存续',
  'score': '84', 'orginalScore': '8491', 'bonusScore': '0', 'companyScore': '84', 'historyNames': None,
  'categoryCode': '', 'industry': None,
  'humanNames': '谢兰芳\t:#0\t;\t钟翔平\t:#0\t;\t王鸣宇\t:#0\t;\t张少宇\t:#0\t;\t杨亚军\t:#1\t;\t李新纳\t:#1\t;\t', 'trademarks': None,
  'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None, 'bondType': None,
  'newtestName': None, 'regNumber': '110000007964437', 'orgNumber': '77155536-2', 'creditCode': '91110108771555362G',
  'businessScope': '地理信息系统的技术开发;技术咨询;技术服务;项目投资;投资管理;车载导航和智能交通;销售计算机软件;硬件;电器设备;交电;财务咨询;货物进出口;技术进出口;代理进出口;经营电信业务',
  'regLocation': '北京市海淀区知春路49号2层224', 'phone': '010-62671188\t;\t010-82173259\t;\t01062671188\t;\t0108217****',
  'phoneList': ['010-6267****', '010-8217****'],
  'phoneInfoList': [{'number': '010-62671188', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '010-82173259', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'}],
  'businessItemList': None, 'phoneNum': '010-6267****',
  'logo': 'https://img5.tianyancha.com/logo/lll/d6d547c4285b02d241cb333eacdd7df7.png@!f_200x200', 'city': '北京市',
  'district': '海淀区', 'emails': 'v_maanzhang@tencent.com\t;\tv_libarli@tencent.com\t;\twinama@tencent.com',
  'emailList': ['v_maanzhang@tencent.com', 'v_libarli@tencent.com', 'winama@tencent.com'], 'websites': '',
  'hiddenPhones': None, 'abbr': '', 'tagList': None, 'companyType': 1, 'companyOrgType': '有限责任公司\t;\t有限责任公司(法人独资)',
  'labelList': None, 'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None,
  'longitude': None, 'legalPersonId': '2234517142', 'legalPersonType': '1', 'distance': None,
  'categoryStr': '科技推广和应用服务业', 'isClaimed': 0, 'claimPkgType': None, 'realClaimPkgType': None, 'baiduUrl': None,
  'isBranch': 0, 'alias': '腾讯大地', 'claimInfo': None, 'hidden': 0, 'legalPersonShowStr': '法定代表人',
  'regCapitalShowStr': '注册资本', 'estiblishTimeShowStr': '成立日期',
  'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'},
                      {'isLink': 1, 'field': '经营范围', 'content': '...的技术...售<em>计算机</em>软件;硬件...'}],
  'labelListV2': ['并购', '企业集团', '曾用名'],
  'labelJsonList': ['{"type":1,"value":"并购"}', '{"type":1,"value":"企业集团"}', '{"type":1,"value":"曾用名"}'],
  'taxCode': '91110108771555362G', 'socialSecurityStaff_num': '586', 'categoryCodeStd': '751', 'hasMorePhone': None,
  'hasVideo': None, 'videoId': None, 'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人',
  'secondPositionShowStr': '注册资本', 'firstPositionValue': '钟翔平', 'secondPositionValue': '6000万人民币', 'bizType': '7',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '6000.0', 'establish_time_long': '1107360000000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 0, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 37009, 'historyRiskCount': 0, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 3100712607, 'name': '河北雄安新区<em>腾讯计算机系统有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '河北',
  'legalPersonName': '沈丹', 'estiblishTime': '2017-09-26 00:00:00.0', 'regCapital': '2000万人民币', 'regStatus': '存续',
  'score': '77', 'orginalScore': '7739', 'bonusScore': '0', 'companyScore': '77', 'historyNames': None,
  'categoryCode': '', 'industry': None, 'humanNames': '沈丹\t:#0\t;\t雷鹏\t:#0\t;\t沈丹\t:#1\t;\t', 'trademarks': None,
  'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None, 'bondType': None,
  'newtestName': None, 'regNumber': '130600000110338', 'orgNumber': 'MA094888-5', 'creditCode': '91130600MA0948885X',
  'businessScope': '计算机软;硬件的设计;技术开发;销售;数据库及计算机互联网络信息服务;系统集成服务;广告设计;代理;制作;发布;网络游戏服务;数据内容服务;数据处理和存储服务',
  'regLocation': '河北省保定市容城县奥威路8号', 'phone': '0312-5678833\t;\t18600763672\t;\t0312567****',
  'phoneList': ['0312-567****', '1860076****'],
  'phoneInfoList': [{'number': '0312-5678833', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '18600763672', 'type': '1', 'source': None, 'comment': '号码可正常联系'}],
  'businessItemList': None, 'phoneNum': '0312-567****',
  'logo': 'https://img5.tianyancha.com/logo/lll/c036e29c0342e6afa9f8eb2ae456e38a.png@!f_200x200', 'city': '保定市',
  'district': '容城县', 'emails': 'hyderli@tencent.com', 'emailList': ['hyderli@tencent.com'], 'websites': '',
  'hiddenPhones': None, 'abbr': '腾讯投资\t:#2#\t;\t', 'tagList': None, 'companyType': 1,
  'companyOrgType': '有限责任公司\t;\t有限责任公司(自然人投资或控股)', 'labelList': None,
  'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None, 'longitude': None,
  'legalPersonId': '2043018292', 'legalPersonType': '1', 'distance': None, 'categoryStr': '软件和信息技术服务业', 'isClaimed': 0,
  'claimPkgType': -2, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': '雄安新区', 'claimInfo': None,
  'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本', 'estiblishTimeShowStr': '成立日期',
  'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'},
                      {'isLink': 1, 'field': '经营范围', 'content': '<em>计算机</em>软;硬...务;<em>系统</em>集成服...'}],
  'labelListV2': ['投资机构', '企业集团', '小微企业'],
  'labelJsonList': ['{"type":1,"value":"投资机构"}', '{"type":1,"value":"企业集团"}', '{"type":1,"value":"小微企业"}'],
  'taxCode': '91130600MA0948885X', 'socialSecurityStaff_num': '0', 'categoryCodeStd': '651', 'hasMorePhone': None,
  'hasVideo': None, 'videoId': None, 'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人',
  'secondPositionShowStr': '注册资本', 'firstPositionValue': '沈丹', 'secondPositionValue': '2000万人民币', 'bizType': '7',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[0,0,0,4]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '2000.0', 'establish_time_long': '1506355200000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 0, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 37009, 'historyRiskCount': 1, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 24468760, 'name': '优扬文化传媒股份<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '北京',
  'legalPersonName': '杨国光', 'estiblishTime': '2008-01-22 00:00:00.0', 'regCapital': '15840万人民币', 'regStatus': '存续',
  'score': '91', 'orginalScore': '9141', 'bonusScore': '0', 'companyScore': '91', 'historyNames': None,
  'categoryCode': '', 'industry': None,
  'humanNames': '杨峥\t:#0\t;\t任飞\t:#0\t;\t生颢\t:#0\t;\t厍寅斌\t:#0\t;\t顾辰\t:#0\t;\t杨国光\t:#0\t;\t仇伟华\t:#0\t;\t游志坚\t:#0\t;\t仇伟华\t:#1\t;\t钟百玲\t:#1\t;\t游志坚\t:#1\t;\t杨国光\t:#1\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None,
  'bondType': None, 'newtestName': None, 'regNumber': '110115010775480', 'orgNumber': '67171468-8',
  'creditCode': '91110108671714688R',
  'businessScope': '发行动画片;电视综艺;专题片;组织文化艺术交流活动;设计;制作;代理;发布广告;承办展览展示;信息咨询;动画设计;技术开发;软件开发',
  'regLocation': '北京市海淀区海淀中街16号5层6单元501',
  'phone': '010-59756248\t;\t010-84357789\t;\t010-84307000\t;\t010-84307067\t;\t01059756248\t;\t01084357789\t;\t01084307000\t;\t0108430****',
  'phoneList': ['010-5975****', '010-8435****', '010-8430****', '010-8430****'],
  'phoneInfoList': [{'number': '010-59756248', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '010-84357789', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '010-84307000', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '010-84307067', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'}],
  'businessItemList': None, 'phoneNum': '010-5975****',
  'logo': 'https://img5.tianyancha.com/logo/lll/400a6a05f665bf414ef2d3b26ef6b076.png@!f_200x200', 'city': '北京市',
  'district': '海淀区', 'emails': 'xiaoli_gao@uyoung.com.cn\t;\tmeng_wang@uyoung.com.cn\t;\txiying_cui@uyoung.com.cn',
  'emailList': ['xiaoli_gao@uyoung.com.cn', 'meng_wang@uyoung.com.cn', 'xiying_cui@uyoung.com.cn'],
  'websites': 'http://www.uyoung.com.cn\t;\twww.uyoung.com.cn\t;\tu-kids.com.cn\t;\tukids.cn\t;\t119.61.6.54\t;\t119.61.6.51\t;\t119.61.6.54\t;\t119.61.6.51\t;\thttp://www.uyoung.com.cn',
  'hiddenPhones': None, 'abbr': '优扬传媒\t:#1#\t;\t', 'tagList': None, 'companyType': 1,
  'companyOrgType': '股份有限公司\t;\t股份有限公司(非上市、自然人投资或控股)', 'labelList': None,
  'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None, 'longitude': None,
  'legalPersonId': '1998862376', 'legalPersonType': '1', 'distance': None, 'categoryStr': '广播、电视、电影和录音制作业',
  'isClaimed': 0, 'claimPkgType': None, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': '优扬',
  'claimInfo': None, 'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本',
  'estiblishTimeShowStr': '成立日期', 'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}],
  'labelListV2': ['B轮', '优扬传媒', '企业集团', '曾用名', '瞪羚企业'],
  'labelJsonList': ['{"type":1,"value":"B轮"}', '{"type":1,"value":"优扬传媒"}', '{"type":1,"value":"企业集团"}',
                    '{"type":1,"value":"曾用名"}', '{"type":1,"value":"瞪羚企业"}'], 'taxCode': '91110108671714688R',
  'socialSecurityStaff_num': '59', 'categoryCodeStd': '879', 'hasMorePhone': None, 'hasVideo': None, 'videoId': None,
  'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人', 'secondPositionShowStr': '注册资本',
  'firstPositionValue': '杨国光', 'secondPositionValue': '15840万人民币', 'bizType': '8',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '15840.0', 'establish_time_long': '1200931200000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 946, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 37191, 'historyRiskCount': 1, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 24852810, 'name': '北京像素软件科技股份<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '北京',
  'legalPersonName': '刘坤', 'estiblishTime': '2002-03-18 00:00:00.0', 'regCapital': '3000万人民币', 'regStatus': '存续',
  'score': '79', 'orginalScore': '7985', 'bonusScore': '0', 'companyScore': '79', 'historyNames': None,
  'categoryCode': '', 'industry': None,
  'humanNames': '刘坤\t:#0\t;\t李江\t:#0\t;\t蒙冰\t:#0\t;\t丁义\t:#0\t;\t孟欣\t:#0\t;\t刘岩\t:#0\t;\t刘豫斌\t:#0\t;\t魏华\t:#0\t;\t王婷婷\t:#0\t;\t刘坤\t:#1\t;\t刘岩\t:#1\t;\t李江\t:#1\t;\t魏华\t:#1\t;\t刘豫斌\t:#1\t;\t孟欣\t:#1\t;\t张佳\t:#1\t;\t蒋黎\t:#1\t;\t刘坤\t:#1\t;\t刘岩\t:#1\t;\t李江\t:#1\t;\t魏华\t:#1\t;\t刘豫斌\t:#1\t;\t蒋黎\t:#1\t;\t张佳\t:#1\t;\t孟欣\t:#1\t;\t卿晓星\t:#1\t;\t张弛\t:#1\t;\t杨纮宇\t:#1\t;\t刘斌\t:#1\t;\t龚静\t:#1\t;\t纪光辉\t:#1\t;\t夏磊\t:#1\t;\t张明\t:#1\t;\t高薇\t:#1\t;\t刘毅\t:#1\t;\t陈卫卫\t:#1\t;\t刘红宇\t:#1\t;\t张朝志\t:#1\t;\t蒙冰\t:#1\t;\t汤晓明\t:#1\t;\t李竞鋆\t:#1\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': '像素软件',
  'bondNum': '836333', 'bondType': '新三板', 'newtestName': None, 'regNumber': '110114003692842',
  'orgNumber': '73647912-2', 'creditCode': '911101147364791227',
  'businessScope': '互联网信息服务;含电子公告服务;软件技术开发;销售玩具;从事互联网文化活动;制作;发行动画片;专题片;电视综艺',
  'regLocation': '北京市昌平区科技园区白浮泉路10号2号楼1104A', 'phone': '010-59046061\t;\t13683297120\t;\t0105904****',
  'phoneList': ['010-5904****', '1368329****'],
  'phoneInfoList': [{'number': '010-59046061', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '13683297120', 'type': '1', 'source': None, 'comment': '号码可正常联系'}],
  'businessItemList': None, 'phoneNum': '010-5904****',
  'logo': 'https://img5.tianyancha.com/logo/lll/ffb523ddcead0f0ea7a77c1861e7082d.png@!f_200x200', 'city': '北京市',
  'district': '昌平区', 'emails': 'office@pixelgame.net\t;\twagntingting@pixelgame.net',
  'emailList': ['office@pixelgame.net', 'wagntingting@pixelgame.net'],
  'websites': 'http://www.pixelgame.net\t;\twww.pixelgame.net\t;\twww.pixelgame.com.cn\t;\twww.pixelgame.net',
  'hiddenPhones': None, 'abbr': '像素软件\t:#1#\t;\t', 'tagList': None, 'companyType': 1,
  'companyOrgType': '股份有限公司\t;\t股份有限公司(非上市、自然人投资或控股)', 'labelList': None,
  'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None, 'longitude': None,
  'legalPersonId': '1809249672', 'legalPersonType': '1', 'distance': None, 'categoryStr': '广播、电视、电影和录音制作业',
  'isClaimed': 0, 'claimPkgType': -2, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': '像素软件',
  'claimInfo': None, 'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本',
  'estiblishTimeShowStr': '成立日期', 'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}],
  'labelListV2': ['新三板 | 正常上市', '像素软件', '瞪羚企业', '高新技术企业'], 'labelJsonList': [
     '{"bondType":"新三板","listingStatus":"正常上市","bondNum":"836333","sort":1,"type":2,"shortName":"像素软件","value":"新三板 | 正常上市"}',
     '{"type":1,"value":"像素软件"}', '{"type":1,"value":"瞪羚企业"}', '{"type":1,"value":"高新技术企业"}'],
  'taxCode': '911101147364791227', 'socialSecurityStaff_num': '354', 'categoryCodeStd': '759', 'hasMorePhone': None,
  'hasVideo': None, 'videoId': None, 'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人',
  'secondPositionShowStr': '注册资本', 'firstPositionValue': '刘坤', 'secondPositionValue': '3000万人民币', 'bizType': '8',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '3000.0', 'establish_time_long': '1016380800000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 41, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 37009, 'historyRiskCount': 1, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 2349883284, 'name': '武汉鲨鱼网络直播技术<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '湖北',
  'legalPersonName': '李大任', 'estiblishTime': '2016-04-07 00:00:00.0', 'regCapital': '125.3325万人民币', 'regStatus': '存续',
  'score': '58', 'orginalScore': '5888', 'bonusScore': '0', 'companyScore': '58', 'historyNames': None,
  'categoryCode': '', 'industry': None,
  'humanNames': '余海洋\t:#0\t;\t何佳\t:#0\t;\t苗壮昌\t:#0\t;\t陈少杰\t:#0\t;\t朱鹏\t:#0\t;\t霍岩\t:#0\t;\t万为\t:#0\t;\t李大任\t:#0\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None,
  'bondType': None, 'newtestName': None, 'regNumber': '420100000615262', 'orgNumber': 'MA4KMAFU-0',
  'creditCode': '91420100MA4KMAFU0L',
  'businessScope': '网络直播及相关领域内的技术开发;技术转让;技术咨询及技术服务;计算机软件及辅助设备的零售;广告设计;代理及发布;经营性互联网文化服务;会议会展服务;第二类增值电信业务;文化创意设计;文化艺术活动交流策划;网站建设;游戏软件设计;演出经纪服务;影视;广播电视节目的设计;制作;发布;互联网信息服务',
  'regLocation': '武汉东湖新技术开发区关山一路1号华中曙光软件园商界2栋4层13号（自贸区武汉片区）（一址多照）',
  'phone': '010-57625681\t;\t13606406169\t;\t0105762****', 'phoneList': ['010-5762****', '1360640****'],
  'phoneInfoList': [{'number': '010-57625681', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '13606406169', 'type': '1', 'source': None, 'comment': '号码可正常联系'}],
  'businessItemList': None, 'phoneNum': '010-5762****',
  'logo': 'https://img5.tianyancha.com/logo/lll/343d90657dfd024c476c99df5bd5b364.png@!f_200x200', 'city': '武汉市',
  'district': '青山区', 'emails': '16152522@qq.com\t;\t800161087@qq.com',
  'emailList': ['16152522@qq.com', '800161087@qq.com'], 'websites': 'http://live.qq.com/', 'hiddenPhones': None,
  'abbr': '企鹅直播\t:#1#\t;\t企鹅直播伴侣\t:#1#\t;\t', 'tagList': None, 'companyType': 1,
  'companyOrgType': '有限责任公司\t;\t有限责任公司(自然人投资或控股)', 'labelList': None,
  'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None, 'longitude': None,
  'legalPersonId': '1981954453', 'legalPersonType': '1', 'distance': None, 'categoryStr': '软件和信息技术服务业', 'isClaimed': 0,
  'claimPkgType': -2, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': '鲨鱼网络', 'claimInfo': None,
  'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本', 'estiblishTimeShowStr': '成立日期',
  'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'},
                      {'isLink': 1, 'field': '经营范围', 'content': '...询及技术服务;<em>计算机</em>软件及辅助设...'}],
  'labelListV2': ['战略融资', '企鹅直播', '企业集团', '小微企业'],
  'labelJsonList': ['{"type":1,"value":"战略融资"}', '{"type":1,"value":"企鹅直播"}', '{"type":1,"value":"企业集团"}',
                    '{"type":1,"value":"小微企业"}'], 'taxCode': '91420100MA4KMAFU0L', 'socialSecurityStaff_num': '22',
  'categoryCodeStd': '659', 'hasMorePhone': None, 'hasVideo': None, 'videoId': None, 'isRecommend': None,
  'englishName': None, 'firstPositionShowStr': '法定代表人', 'secondPositionShowStr': '注册资本', 'firstPositionValue': '李大任',
  'secondPositionValue': '125.3325万人民币', 'bizType': '7',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '125.3325', 'establish_time_long': '1459958400000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 5, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 37975, 'historyRiskCount': 2, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 2349048332, 'name': '浙江齐聚科技<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '浙江',
  'legalPersonName': '汪海滨', 'estiblishTime': '2008-12-12 00:00:00.0', 'regCapital': '1452.4787万人民币', 'regStatus': '存续',
  'score': '74', 'orginalScore': '7468', 'bonusScore': '0', 'companyScore': '74', 'historyNames': None,
  'categoryCode': '', 'industry': None,
  'humanNames': '席晗\t:#0\t;\t张孝超\t:#0\t;\t彭丹\t:#0\t;\t李德来\t:#0\t;\t汪海滨\t:#0\t;\t王永强\t:#0\t;\t罗莹莹\t:#0\t;\t高飞飞\t:#0\t;\t汪海滨\t:#1\t;\t王永强\t:#1\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None,
  'bondType': None, 'newtestName': None, 'regNumber': '330701000018937', 'orgNumber': '68313493-9',
  'creditCode': '91330701683134939N',
  'businessScope': '软件开发与设计;网络系统集成;网络工程设计;网站设计与开发;通信系统开发集成;网络技术开发;电子产品研究;通信技术开发;软件销售;电信业务;经营性互联网文化服务;广播电视节目制作;经营演出经纪业务;文化艺术交流活动策划;市场营销策划;信息技术咨询',
  'regLocation': '浙江省金华市婺城区四联路398号金华网络经济中心大楼1302室',
  'phone': '0579-89809688\t;\t0579-89809696\t;\t0579-89809695\t;\t010-57835800\t;\t010-58103228\t;\t057989809688\t;\t057989809696\t;\t057989809695\t;\t01057835800\t;\t0105810****',
  'phoneList': ['0579-8980****', '0579-8980****', '0579-8980****', '010-5783****', '010-5810****'],
  'phoneInfoList': [{'number': '0579-89809688', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '0579-89809696', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '0579-89809695', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '010-57835800', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '010-58103228', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'}],
  'businessItemList': None, 'phoneNum': '0579-8980****',
  'logo': 'https://img5.tianyancha.com/logo/lll/6765e2ad61f29f5824b0c16fe3aaf4d1.png@!f_200x200', 'city': '金华市',
  'district': '婺城区', 'emails': '', 'emailList': None,
  'websites': 'pingguo55.cn\t;\tjuxing55.cn\t;\tqixi55.net\t;\tguagua55.com\t;\timg002.com\t;\tyese55.cn\t;\twww.re58.cn\t;\twww.meimeiliao55.com\t;\twww.pingguo55.com\t;\twww.juxing55.com\t;\twww.qixi55.com\t;\twww.guagua.com.cn\t;\twww.img001.com\t;\twww.yese55.com\t;\twww.re73.cn\t;\thttp://iqiju.com',
  'hiddenPhones': None, 'abbr': '呱呱视频社区\t:#1#\t;\t呱呱财经\t:#1#\t;\t齐聚科技\t:#1#\t;\t齐齐直播\t:#1#\t;\t', 'tagList': None,
  'companyType': 1, 'companyOrgType': '有限责任公司\t;\t有限责任公司(自然人投资或控股)', 'labelList': None,
  'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None, 'longitude': None,
  'legalPersonId': '2041916938', 'legalPersonType': '1', 'distance': None, 'categoryStr': '软件和信息技术服务业', 'isClaimed': 0,
  'claimPkgType': None, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': '齐聚科技', 'claimInfo': None,
  'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本', 'estiblishTimeShowStr': '成立日期',
  'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'},
                      {'isLink': 1, 'field': '经营范围', 'content': '...;网络<em>系统</em>集成;...开发...'}],
  'labelListV2': ['并购', '呱呱视频社区', '企业族群', '高新技术企业', '曾用名', '小微企业'],
  'labelJsonList': ['{"type":1,"value":"并购"}', '{"type":1,"value":"呱呱视频社区"}', '{"type":1,"value":"企业族群"}',
                    '{"type":1,"value":"高新技术企业"}', '{"type":1,"value":"曾用名"}', '{"type":1,"value":"小微企业"}'],
  'taxCode': '91330701683134939N', 'socialSecurityStaff_num': '48', 'categoryCodeStd': '651', 'hasMorePhone': None,
  'hasVideo': None, 'videoId': None, 'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人',
  'secondPositionShowStr': '注册资本', 'firstPositionValue': '汪海滨', 'secondPositionValue': '1452.4787万人民币', 'bizType': '7',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '1452.4787', 'establish_time_long': '1229011200000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 6, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 37202, 'historyRiskCount': 0, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 1259830376, 'name': '广州市擎天柱网络科技<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '广东',
  'legalPersonName': '魏坤松', 'estiblishTime': '2010-04-14 00:00:00.0', 'regCapital': '3233.749382万人民币',
  'regStatus': '存续', 'score': '81', 'orginalScore': '8020', 'bonusScore': '1', 'companyScore': '80',
  'historyNames': None, 'categoryCode': '', 'industry': None,
  'humanNames': 'LUPENG\t:#0\t;\t梁洁雯\t:#0\t;\t梁璐\t:#0\t;\t荀为谦\t:#0\t;\t魏剑鸿\t:#0\t;\t魏坤松\t:#0\t;\t黄凌冬\t:#0\t;\t魏剑鸿\t:#1\t;\t魏坤松\t:#1\t;\t张俊民\t:#1\t;\t章洪根\t:#1\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None,
  'bondType': None, 'newtestName': None, 'regNumber': '440106000192043', 'orgNumber': '55239829-9',
  'creditCode': '914401155523982993',
  'businessScope': '新材料技术研发;技术服务;技术开发;技术咨询;技术交流;技术转让;技术推广;计算机软硬件及辅助设备零售;数字文化创意技术装备销售;数字文化创意软件开发;专业设计服务;人工智能应用软件开发;信息技术咨询服务;软件外包服务;动漫游戏开发;网络技术服务;网络与信息安全软件开发;软件开发;计算机系统服务;数字文化创意内容应用服务;数字内容制作服务;文艺创作;咨询策划服务;互联网信息服务;第二类增值电信业务;游艺娱乐活动;技术进出口',
  'regLocation': '广州市天河区科韵路24-26号北楼第八层809房', 'phone': '020-85539716\t;\t18825150517\t;\t0208553****',
  'phoneList': ['020-8553****', '1882515****'],
  'phoneInfoList': [{'number': '020-85539716', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '18825150517', 'type': '1', 'source': None, 'comment': '号码可正常联系'}],
  'businessItemList': None, 'phoneNum': '020-8553****',
  'logo': 'https://img5.tianyancha.com/logo/lll/3f883f867e7aa307b9c9301ee1cf1c1e.png@!f_200x200', 'city': '广州市',
  'district': '天河区',
  'emails': 'qtzadm@175game.com\t;\thr@175game.com\t;\t105464919@qq.com\t;\tqtzadn.@175game.com\t;\twdh0454@175game.com',
  'emailList': ['qtzadm@175game.com', 'hr@175game.com', '105464919@qq.com', 'qtzadn.@175game.com',
                'wdh0454@175game.com'],
  'websites': 'http://www.175game.com\t;\t175game.com\t;\twww.175game.com.cn\t;\t175game.com\t;\t175game.com.cn',
  'hiddenPhones': None, 'abbr': '擎天柱产品\t:#1#\t;\t', 'tagList': None, 'companyType': 1,
  'companyOrgType': '有限责任公司\t;\t有限责任公司(自然人投资或控股)', 'labelList': None,
  'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None, 'longitude': None,
  'legalPersonId': '2288622682', 'legalPersonType': '1', 'distance': None, 'categoryStr': '软件和信息技术服务业', 'isClaimed': 0,
  'claimPkgType': -1, 'realClaimPkgType': -1, 'baiduUrl': None, 'isBranch': 0, 'alias': '擎天柱', 'claimInfo': None,
  'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本', 'estiblishTimeShowStr': '成立日期',
  'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'},
                      {'isLink': 1, 'field': '经营范围', 'content': '...推广;<em>计算机</em>软硬件...'}],
  'labelListV2': ['股权融资', '擎天柱产品', '企业集团', '高新技术企业', '瞪羚企业'],
  'labelJsonList': ['{"type":1,"value":"股权融资"}', '{"type":1,"value":"擎天柱产品"}', '{"type":1,"value":"企业集团"}',
                    '{"type":1,"value":"高新技术企业"}', '{"type":1,"value":"瞪羚企业"}'], 'taxCode': '914401155523982993',
  'socialSecurityStaff_num': '96', 'categoryCodeStd': '732', 'hasMorePhone': None, 'hasVideo': None, 'videoId': None,
  'isRecommend': None, 'englishName': None, 'firstPositionShowStr': '法定代表人', 'secondPositionShowStr': '注册资本',
  'firstPositionValue': '魏坤松', 'secondPositionValue': '3233.749382万人民币', 'bizType': '7',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '3233.749382', 'establish_time_long': '1271174400000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 25, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 37014, 'historyRiskCount': 3, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None},
 {'id': 2313221011, 'name': '广东腾南网络信息科技<em>有限公司</em>', 'type': 1, 'matchType': '股东信息匹配', 'base': '广东',
  'legalPersonName': '郑君', 'estiblishTime': '2011-08-08 00:00:00.0', 'regCapital': '1000万人民币', 'regStatus': '存续',
  'score': '73', 'orginalScore': '7332', 'bonusScore': '0', 'companyScore': '73', 'historyNames': None,
  'categoryCode': '', 'industry': None,
  'humanNames': '王娟\t:#0\t;\t肖曼丽\t:#0\t;\t谢思文\t:#0\t;\t郑君\t:#0\t;\t李闻哲\t:#0\t;\t易海燕\t:#0\t;\t潘静波\t:#0\t;\t栾娜\t:#0\t;\t艾兰\t:#0\t;\t冯昭颖\t:#0\t;\t张磊\t:#0\t;\t',
  'trademarks': None, 'tmList': None, 'productList': None, 'usedBondName': None, 'bondName': None, 'bondNum': None,
  'bondType': None, 'newtestName': None, 'regNumber': '440101000174543', 'orgNumber': '57998288-2',
  'creditCode': '914401015799828821',
  'businessScope': '软件开发;数据处理和存储服务;广告业;策划创意服务;软件零售;通信线路和设备的安装;信息系统集成服务;房地产中介服务;房地产咨询服务;对外承包工程业务;大型活动组织策划服务;大型活动指晚会;运动会;庆典;艺术和模特大赛;艺术节;电影节及公益演出;展览等;计算机批发;软件批发;物联网技术研究开发;网络技术的研究;开发;计算机技术开发;技术服务;会议及展览服务;计算机网络系统工程服务;电子设备工程安装服务;票务服务;计算机零售;智能化安装工程服务;企业形象策划服务;监控系统工程安装服务;通信系统工程服务;商品信息咨询服务;电子产品零售;软件服务;文学;艺;美;术经纪代理服务;增值电信服务;业务种类以;物联网服务;网上新闻服务;网络音乐服务;网上视频服务;网上图片服务;网上动漫服务;无线广播电视传输服务;营业性文艺表演',
  'regLocation': '广州市越秀区广州大道中289号南方传媒大厦B座九楼全层（仅限办公用途）',
  'phone': '020-66849899\t;\t020-66849818\t;\t020-66849858\t;\t02066849899\t;\t02066849818\t;\t0206684****',
  'phoneList': ['020-6684****', '020-6684****', '020-6684****'],
  'phoneInfoList': [{'number': '020-66849899', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '020-66849818', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'},
                    {'number': '020-66849858', 'type': '9', 'source': None, 'comment': '固定电话或非大陆号码'}],
  'businessItemList': None, 'phoneNum': '020-6684****',
  'logo': 'https://img5.tianyancha.com/logo/lll/d45240271ea7be4e6bb71dcb05a7acc2.png@!f_200x200', 'city': '广州市',
  'district': '越秀区', 'emails': 'shirleyluo@gdtengnan.com\t;\tharveyzhou@gdtengnan.com',
  'emailList': ['shirleyluo@gdtengnan.com', 'harveyzhou@gdtengnan.com'],
  'websites': 'http://GD.QQ.COM\t;\twww.gdtengnan.com\t;\twww.regionalhr.com', 'hiddenPhones': None,
  'abbr': '大粤网\t:#1#\t;\t腾讯投资\t:#2#\t;\t', 'tagList': None, 'companyType': 1, 'companyOrgType': '有限责任公司\t;\t其他有限责任公司',
  'labelList': None, 'matchField': {'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'}, 'latitude': None,
  'longitude': None, 'legalPersonId': '2216122190', 'legalPersonType': '1', 'distance': None, 'categoryStr': '研究和试验发展',
  'isClaimed': 0, 'claimPkgType': None, 'realClaimPkgType': None, 'baiduUrl': None, 'isBranch': 0, 'alias': '腾南网络',
  'claimInfo': None, 'hidden': 0, 'legalPersonShowStr': '法定代表人', 'regCapitalShowStr': '注册资本',
  'estiblishTimeShowStr': '成立日期', 'multiMatchField': [{'field': '股东信息', 'content': '<em>深圳市腾讯计算机系统有限公司</em>'},
                                                      {'isLink': 1, 'field': '经营范围',
                                                       'content': '...成服...;<em>计算机</em>...;<em>计算机</em>...'}],
  'labelListV2': ['大粤网', '投资机构', '企业集团', '高新技术企业'],
  'labelJsonList': ['{"type":1,"value":"大粤网"}', '{"type":1,"value":"投资机构"}', '{"type":1,"value":"企业集团"}',
                    '{"type":1,"value":"高新技术企业"}'], 'taxCode': '914401015799828821', 'socialSecurityStaff_num': '139',
  'categoryCodeStd': '651', 'hasMorePhone': None, 'hasVideo': None, 'videoId': None, 'isRecommend': None,
  'englishName': None, 'firstPositionShowStr': '法定代表人', 'secondPositionShowStr': '注册资本', 'firstPositionValue': '郑君',
  'secondPositionValue': '1000万人民币', 'bizType': '7',
  'docFeature': '{"isFollowed":0,"isMonitored":0,"historyClicks":0,"byAnn":0,"timeClicks":[]}',
  'contantMap': {'recallSrc': 'ES', 'param_reg_capital': '1000.0', 'establish_time_long': '1312732800000'},
  'companyPhoneBook': None, 'companyQuestions': None, 'selfRiskCount': 174, 'legalPersonLogo': None,
  'legalPersonAlias': None, 'relatedRiskCount': 37068, 'historyRiskCount': 1, 'followLabel': None, 'contentType': 1,
  'normalWord': None, 'suggestWordList': None, 'companyHumanInfo': None, 'phoneType': None, 'phoneTips': None,
  'publicSentimentNewsInfo': None, 'enterpriseServiceGoodsInfo': None, 'qfLabels': None, 'productShowMore': None,
  'goodsAndProducts': None, 'shortVideoList': None, 'focusCompanyList': None, 'isBrandArea': 0, 'areaType': 0,
  'customizedImagePath': '', 'isBrandAreaControlGroup': 0, 'adsFlag': None, 'isCooperationShow': None,
  'cooperationUrl': '', 'albumHeadImgPath': None, 'albumCount': None, 'websiteUrl': None, 'websiteRiskType': None,
  'hotMsg': None, 'hotType': None, 'competitorName': None, 'brandInstitutionGroupCard': None, 'publishDemandCard': None,
  'appDynamicCompanyCard': None}]
